# Generated by Django 5.1.4 on 2025-01-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_mebel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='description',
            field=models.TextField(verbose_name='Описание с куфар'),
        ),
        migrations.AlterField(
            model_name='mebel',
            name='pars_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода к нам'),
        ),
    ]
